rust-fuzz/afl.rs

- src/afl_cov_rt.c
Was running into this issue when compiling on OSX:
```
error: use of undeclared identifier 'MAP_ANONYMOUS'
```
Did a Google search and came across:
https://j.ee.washington.edu/trac/gmtk/ticket/371
Applied that patch to the .c file and things seem to work
> OSX uses MAP_ANON instead of MAP_ANONYMOUS

- src/lib.rs
`rt::unwind` has been removed from Rust. For this reason this crate stopped compiling on current nightly.
To crash on panic the compiler option `-Z no-landing-pads` can be set.
> Remove rt::unwind

- plugin/src/afl-llvm-pass.so.cc
src/afl-llvm-pass.so.cc:82:49: error: format '%u' expects argument of type 'unsigned int*', but argument 3 has type 'int*' [-Werror=format=]
Signed-off-by: Marc-Antoine Perennou <Marc-Antoine@Perennou.com>
> plugin: fix build

- Cargo.toml
- afl-sys/fuzz.rs
- src/bin/cargo-afl-fuzz.rs
This is just afl-fuzz, but doesn't require the user to install afl-fuzz separately. It also sets `AFL_DEFER_FORKSRV`.
> Introduce 'cargo afl-fuzz'.

- CHANGES.md
- Cargo.toml
- afl-plugin/Cargo.toml
- afl-sys/Cargo.toml
- afl-sys/fuzz.rs
Otherwise, when we run `cargo afl-fuzz`, `cargo` will get passed, which
we don't want.
> Don't pass extra values to C afl-fuzz `main`.

- afl-sys/fuzz.rs
It was found using [mwic](http://jwilk.net/software/mwic).
> Remove duplicated word in a comment

- .travis.yml
I need to do testing with the latest LLVM upgrade before proceeding.
> Lock nightly to version before LLVM upgrade.

- afl-sys/build.rs
I'd love to fix these upstream but there appears to be no trivial way to
do so.
> Silence C compiler warnings when building AFL.

- afl-sys/fuzz.rs
- src/lib.rs
The 'queue' directory gets created, regardless of whether AFL actually
ran or not, unlike the 'fuzzer_stats' file.
> Check for existence of 'fuzzer_stats' file for integration test, fix afl-sys on Linux.

- README.md
I think this was the intention and fixes this from the "What is it" paragraph:
`[the Rust programming language][rust].`
Making markdown interpret it as a link instead.
> Add rust-lang.org markdown link

- src/common.rs
This ensure that cargo-afl needs to be rebuilt if one updates their
nightly Rust to a newer nightly Rust.
> Incorporate commit hash into directory structure.

- .travis.yml
- Cargo.lock
- src/bin/cargo-afl.rs
- src/lib.rs
See the commits for more details
Performance goes from ~2400/s to ~19500/s on `url_read` target on i7-7700HQ.
>  Implement persistent mode + use panic::set_hook() + many more

- src/bin/cargo-afl.rs
Per issue #142, `cargo afl test` and other commands that would run
doctests would encounter issues with linkage. This commit changes `cargo
afl` to set RUSTDOCFLAGS so rustdoc will be able to find the required
libs. Further options are passed to ensure doctests are built and run in
as similar a fashion to other code. This avoids other gotchas like cfg
fuzzing being set for normal builds, but not for doctests.
> Set RUSTDOCFLAGS to avoid issues with linkage for doctests.

- src/bin/cargo-afl.rs
rust-fuzz/afl.rs#141 + rust-lang/rust#53945 track issues with linkage
which regressed when rust updated to llvm 8. This commit adds a work
around for such issues for cargo-afl. This helps with the ergonomics of
cargo-afl, particularly for those less familiar with the project and the
above issues.
These changes can be safely removed once patches are landed in llvm and
rust updates to use the patched version.
> Work around linking issues from rust-fuzz/afl.rs#141, rust-lang/rust#53945

- build.rs
Installing `afl.rs` on ARM results in this error:
```
$ cargo build
...
Oops, looks like your compiler can't generate x86 code.
Don't panic! You can use the LLVM or QEMU mode, but see docs/INSTALL first.
(To ignore this error, set AFL_NO_X86=1 and try again.)
Makefile:52: recipe for target 'test_x86' failed
--- stderr
/tmp/ccI7TNQZ.s: Assembler messages:
/tmp/ccI7TNQZ.s:28: Error: bad instruction `xorb %al,%al'
```
To fix, we can add another `.env()` mapping to set `AFL_NO_X86` when executing `build_afl()` on ARM.
> Add build support for AFL on ARM

- src/lib.rs
If your fuzzing code catches panics somewhere inside its code the hook would turn those into crashes. Allow disabling the hook by adding a fuzz_nohook! macro.
Even in empty targets the hook causes variability in the execution of the code somehow. That reduces the stability of the fuzzing making it less effective.
Fixes #150
> Add a fuzz! version that doesn't hook panics

- src/bin/cargo-afl.rs
The #141 workaround was actually fully disabled because the OS condition
was wrong. This fixes the workaround.
> Fix broken OS detection

- src/lib.rs
I'd like to be able to use the methods in common to find the afl built by afl.rs as part of a crate I'm working on's build system.
I'm not strongly wed to this approach, so any feedback is welcome!
> Expose common in the public API

- src/lib.rs
The common elements of the `fuzz!` and `fuzz_nohook!` macros are consolidated into a single macro, `__fuzz!`.  The `fuzz!` and `fuzz_nohook!` macros are accordingly altered to use `__fuzz!`.  Eliminating this redundancy should facilitate maintainability.
> Eliminate fuzz/fuzz_nohook redundancy

- src/lib.rs
Fixes #160 
About stability:
* afl.rs does not contain tests, so I could not run them. After this change afl.rs builds, and I can use the macro with FnMut function.
* I'm not expert with UnwindSafe, so not sure if this change produces side effects
> Accept FnMut instead of Fn

- Cargo.lock
- Cargo.toml
- src/bin/cargo-afl.rs
This PR adds a new option to `cargo afl fuzz`, `--max_total_time`, to limit how long afl-fuzz runs for. The new option will enable implementing rust-fuzz/targets#107. When this option is specified, `cargo-afl` will wait that many seconds and kill `afl-fuzz`, if it's still running. I had to refactor how command line arguments were passed around, as well, so that this new option didn't get passed to `afl`.
> Add option to kill afl-fuzz after a time limit

- Cargo.toml
- README.md
- src/lib.rs
This PR addresses #164.
As promised in that issue, this PR:
* adds a call to `lazy_static::lazy::reset()`, guarded by a new feature, `reset_lazy_static`, and
* updates the README with instructions on how to use the new feature.
The changes are tested by [this project](https://github.com/smoelius/fuzz-lazy-static).
Regarding the latter bullet, I considered whether the instructions would be better suited for the rust-fuzz book. Ultimately, I wasn't sure where they should go in the book, so I went ahead with the README.
Anyway, I am very much open to suggestions regarding the instructions, both in their content and their placement.
> Use resettable-lazy-static.rs

- build.rs
hard-code the path to ar as /usr/bin/ar in the build on mac to avoid dependency leaks
> Hard-code the path to ar as /usr/bin/ar

- src/lib.rs
#161 introduced the `__fuzz!` macro, but did not refer to it with a qualified path. Consequently, users of afl.rs were forced to bring `afl::__fuzz` into their namespace, e.g., with `use afl::*`. This PR qualifies the uses of `__fuzz!` so that such a practice is no longer necessary.
For example, the following programs now compile, whereas they wouldn't before:
```rust
fn main() {
afl::fuzz!(|data: &[u8]| {});
}
```
```rust
use afl::fuzz;
fn main() {
fuzz!(|data: &[u8]| {});
}
```
> Qualify uses of `__fuzz!` macro

- build.rs
- src/lib.rs
Persistent shared memory gives a speedup of ~2x and improves by a lot the scalability over multiple cores.
For instance, for the url-fuzz-example, on my laptop, I get 40k execs/sec with this patch vs. the 26 execs/sec with the current afl.rs.
I suggest you also to enable trace-cmp, maybe with a custom build option, to produce a CmpLog binary (https://github.com/AFLplusplus/AFLplusplus/blob/stable/instrumentation/README.cmplog.md) that improves a lot in terms of coverage when used to bypass comparisons.
This closes #173
> update to AFL++ 3.01a && enable persistent shared memory fuzzing

- src/common.rs
I haven't tested it, but this code should be enough to get `afl` to compile for docs.rs 
See https://docs.rs/crate/afl/0.10.0/builds/351937 for the current errors. This will require a new release to test.
> Use local directories when building for docs.rs

- src/bin/cargo-afl.rs
Fixes #192
This drops support for the old nightly, but that should be fine. (See discussion in cargo-fuzz: https://github.com/rust-fuzz/cargo-fuzz/pull/277)
> Update for new LLVM pass manager

- src/bin/cargo-afl.rs
The new LLVM pass manager was not enabled in rustc 1.57 as expected: https://github.com/rust-lang/rust/pull/91263
The proposed fix to only pass `-C passes=sancov-module` to nightly compilers for which the LLVM version is >= 13.
Closes #192
@taiki-e Perhaps you could look this over.
> Handle old LLVM pass manager on rustc 1.57

- Cargo.lock
- Cargo.toml
- src/lib.rs
`tempdir` crate has been deprecated.
https://github.com/rust-lang-deprecated/tempdir#deprecation-note
> ## Deprecation Note
> The tempdir crate is being merged into tempfile and is available in 3.x. Please direct new issues and pull requests to tempfile.
See also https://rustsec.org/advisories/RUSTSEC-2018-0017.html.
> Replace deprecated tempdir with tempfile

- Cargo.toml
- src/common.rs
- src/lib.rs
This change addresses the same problem as #185. It turns out that build scripts are only meant to write to `OUT_DIR`, and in general it is untidy to write things all over the place. docs.rs is specially sensitive to this.
Also, docs.rs does not set the feature flag `docsrs` by itself, but a Cargo package metadata section can be used to instruct docs.rs to pass that flag to Cargo.
I have not tested the change.
> Do not write to user data directories on build. Fix docs.rs documentation generation

- build.rs
This PR does two things:
1. Attempts to address the docs.rs problem (see #231, #249, #250) by building AFL in `OUT_DIR`
2. Displays the output of any failed command in build.rs
> Build AFL in a temporary directory in `OUT_DIR`

- .github/workflows/rust.yml
- .github/workflows/update_aflplusplus.yml
This workflow determines the latest release of [AFLpluplus](https://github.com/AFLplusplus/AFLplusplus), and opens a PR to update the git submodule if that release is different than the one currently used.
> Add `Update AFLplusplus` workflow

- Cargo.toml
- src/bin/cargo-afl.rs
This is to allow not setting 'fuzzing' flag when compiling fuzzed targets.
Some crates (eg. secp256k1) stub some functions, when they detect 'fuzzing' flag, which makes them useless when fuzzing.
This is to address issue #305
> Add optional feature 'no_cfg_fuzzing'

- build.rs
This was @vkleen's [original proposal](https://github.com/rust-fuzz/afl.rs/commit/b7db11193ccea2a251af76a39d29d3c99f5ccacf) in #248. See #316 for the reasons why we are now doing this.
> Unconditionally remove `DEBUG` environment variable

- examples/cmplog.rs
- src/bin/cargo-afl.rs
As suggested in #323, CmpLog could be added to afl.rs to improve effectiveness.
Testing this change on the following example will find the crash **immediately** instead of after a minute.
I can see no performance drop, some more benchmarking might be needed.
You need to specify the `-c 0` option (or `-c path/to/your/binary`).
```rust
fn main() {
afl::fuzz!(|data: &[u8]| {
if data.len() != 6 {return}
if data[0] != b'q' {return}
if data[1] != b'w' {return}
if data[2] != b'e' {return}
if data[3] != b'r' {return}
if data[4] != b't' {return}
if data[5] != b'y' {return}
panic!("BOOM")
});
}
```
I also tried adding the following flags but they resulted in compilation errors of the target.
```
-C llvm-args=-sanitizer-coverage-trace-geps \
-C llvm-args=-sanitizer-coverage-trace-loads \
-C …
```
> Add mini CmpLog

- Cargo.lock
- afl/Cargo.toml
- cargo-afl/Cargo.toml
Version 0.14.0 failed to include the AFLplusplus submodule.
> Bump version

- README.md
- afl/build.rs
- cargo-afl/src/bin/cargo-afl.rs
This is to address issue https://github.com/rust-fuzz/afl.rs/issues/397
In order to prevent `cargo-afl` from setting `fuzzing` flag one needs to set `AFL_NO_CFG_FUZZING` environmental variable.
Eg.
```
AFL_NO_CFG_FUZZING=1 cargo afl build 
```
> Fix running AFL with no 'fuzzing' flag

- cargo-afl/src/bin/cargo-afl.rs
See https://github.com/rust-fuzz/afl.rs/pull/407#issuecomment-1787546026.
> Check subcommands' statuses

- cargo-afl/src/bin/cargo-afl.rs
> add addseeds command

- .github/workflows/rust.yml
- afl/examples/cmplog.rs
- cargo-afl/Cargo.toml
- cargo-afl/build.rs
- cargo-afl/src/bin/cargo-afl.rs
- cargo-afl/src/common.rs
This PR activates full cmplog by compiling the afl++ llvm plugins and linking them into the target binaries.
This is activated via an added features "cmplog" as it needs nightly and llvm tools. It is not activated by default.
This fixes #323 .
> Add plugins feature

- cargo-afl/build.rs
Version 0.14.5 removed this setting ([here](
https://github.com/rust-fuzz/afl.rs/commit/785db302eedda71b9702bdc2d63eb824ba529991#diff-2d8fbbc60fb70d8a96ce3da99b3d4b4499282482677ed0c50fd13f792cbf5af4R78) and [here](
https://github.com/rust-fuzz/afl.rs/commit/ce3397f4cc6207dedd217f10febb25f5cd9c0f68#diff-2d8fbbc60fb70d8a96ce3da99b3d4b4499282482677ed0c50fd13f792cbf5af4L78)), which significantly increased build times.
This PR reintroduces the setting when the `plugins` feature is not enabled.
> Reintroduce `NO_BUILD=1`

- .github/workflows/rust.yml
- cargo-afl/Cargo.toml
- cargo-afl/build.rs
- cargo-afl/src/common.rs
- cargo-afl/src/config.rs
- cargo-afl/src/main.rs
- cargo-afl/tests/crates_io.rs
This PR adds a subcommand `config` to manage building AFL++. The intent is to decouple the cargo-afl installation from the Rust toolchain used to install it.
No longer will it be necessary to reinstall cargo-afl following a `rustup update`. Instead, the following will be possible:
```sh
cargo install cargo-afl          # Install cargo-afl and build AFL++ for the default toolchain
rustup update                    # Update the default toolchain
cargo afl config --build --force # Rebuild AFL++ for the default toolchain
```
Another example:
```sh
cargo +nightly install cargo-afl # Install cargo-afl and build AFL++ using the nightly toolchain
cargo afl config --build         # Build AFL++ for the default (e.g., stable) toolchain
```
Note that the cargo-afl installation is still tied to a …
> Add `config` subcommand

- .github/workflows/rust.yml
From [Defining prerequisite jobs](https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow#defining-prerequisite-jobs):
> If you would like a job to run even if a job it is dependent on did not succeed, use the `always()` conditional expression in `jobs.<job_id>.if`.
> Correct logic in `all-checks`

- afl/src/lib.rs
> Allow setting `__afl_persistent_loop` argument (support for #433)

- cargo-afl/src/main.rs
**Bug 1**
This PR fixes just the major issue: when nightly is used and plugins are compiled - then still the default bad sancov of LLVM is used, because -C sancov is always passed.
_I sadly have no time to fix the other two bugs, too time constraint :(_
**Bug 2**
Another issue I found and not fixed in this PR:
AFL++'s LLVM plugins are not built by default.
And even if the user wants to build them the check is faulty:
```
$ cargo-afl afl config --plugins
AFL LLVM runtime was already built for Rust rustc-1.75.0-nightly-42b1224; run `cargo afl config --build --force` to rebuild it.
$ ls /home/marc/.local/share/afl.rs/rustc-1.75.0-nightly-42b1224/afl.rs-0.15.1/afl-llvm
libafl-llvm-rt.a  libafl-llvm-rt.o
```
The message says "runtime" which would be correct, because the runtime is there, but …
> Do not pass `-C passes=...` when nightly is used and plugins are compiled

- .github/workflows/rust.yml
See: https://github.com/llvm/llvm-project/issues/99502
> Temporarily add `ubuntu-24.04` as a target, and remove `ubuntu-latest`

- cargo-afl/tests/crates_io.rs
When run with the nightly toolchain, the `publish` test recently started failing with the following:
```
error: crate afl@0.15.10 already exists on crates.io index
```
I think this is the cause: https://github.com/rust-lang/cargo/blob/6ede1e2b276eaf93618765a08bd3ec2f0f44d955/src/cargo/ops/registry/publish.rs#L136
See, for example: https://github.com/rust-lang/cargo/pull/14550/files#r1763454347
> Change `publish` test to `package` test

- cargo-afl/src/main.rs
``rustc`` will complain if an invalid ``opt-level`` is provided so we don't really need to check the value, IMO
> introduce AFLRS_REQUIRE_PLUGINS & AFL_OPT_LEVEL

- .github/workflows/rust.yml
`ubuntu-latest` is Ubuntu 24.04 now.
> Remove Ubuntu 24.04 environment

- Cargo.toml
This recent change is causing CI to fail: https://github.com/rust-lang/rust/pull/132577
The failure is caused by the `used_linker` feature in code produced by the `ctor::ctor` attribute macro.
> Allowing the `unexpected_cfgs` lint

- cargo-afl/src/main.rs
the ``split-switches-pass`` was missing for AFL++'s cmplog instrumentation. And also, the order of the passes matters so I re-ordered them in the same order as AFL++'s ``afl-cc.c``
> Add split-switches-pass to AFL++ instrumentation

- Cargo.lock
- Cargo.toml
> Revert "Allowing the `unexpected_cfgs` lint"

- cargo-afl/src/main.rs
If I am tracking the history right, use of the gold linker was added in this PR: https://github.com/rust-fuzz/afl.rs/pull/144
However, nightly rust has started passing `"-Wl,-znostart-stop-gc"`, and gold doesn't recognize that option:
```
+  = note: /usr/bin/ld.gold: nostart-stop-gc: unknown -z option
```
See: https://github.com/rust-lang/rust/pull/137685
> Eliminate use of gold linker

- cargo-afl/src/common.rs
- cargo-afl/src/config.rs
- cargo-afl/src/main.rs
Eliminate the use of archives as per @vanhauser-thc's comment here: https://github.com/rust-fuzz/afl.rs/pull/655#issuecomment-3332854417
> Remove archive
